// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATuoRbViajwWD5v6IiNNDWGPidx8Cn_AY',
    appId: '1:610052229774:web:1c38557401d49f715bd7df',
    messagingSenderId: '610052229774',
    projectId: 'smart-home-automation-a052e',
    authDomain: 'smart-home-automation-a052e.firebaseapp.com',
    databaseURL: 'https://smart-home-automation-a052e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-automation-a052e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJesrQcpNg9lr59zZuQxSjhtW9yVH3fAk',
    appId: '1:610052229774:android:990862fcb7e1c2de5bd7df',
    messagingSenderId: '610052229774',
    projectId: 'smart-home-automation-a052e',
    databaseURL: 'https://smart-home-automation-a052e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-automation-a052e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAnyGSr89s6gypyC9KDvc5LuQVQcFvDA',
    appId: '1:610052229774:ios:9a1d25645aff23b05bd7df',
    messagingSenderId: '610052229774',
    projectId: 'smart-home-automation-a052e',
    databaseURL: 'https://smart-home-automation-a052e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-automation-a052e.appspot.com',
    androidClientId: '610052229774-9fp6gj35sdak0ch4sbecp0ak5qtm6aik.apps.googleusercontent.com',
    iosClientId: '610052229774-s4oup0fsoifhbms0v51bdajprluekofc.apps.googleusercontent.com',
    iosBundleId: 'com.example.http',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAnyGSr89s6gypyC9KDvc5LuQVQcFvDA',
    appId: '1:610052229774:ios:9a1d25645aff23b05bd7df',
    messagingSenderId: '610052229774',
    projectId: 'smart-home-automation-a052e',
    databaseURL: 'https://smart-home-automation-a052e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-automation-a052e.appspot.com',
    androidClientId: '610052229774-9fp6gj35sdak0ch4sbecp0ak5qtm6aik.apps.googleusercontent.com',
    iosClientId: '610052229774-s4oup0fsoifhbms0v51bdajprluekofc.apps.googleusercontent.com',
    iosBundleId: 'com.example.http',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATuoRbViajwWD5v6IiNNDWGPidx8Cn_AY',
    appId: '1:610052229774:web:b2ed53e6e43b8d6c5bd7df',
    messagingSenderId: '610052229774',
    projectId: 'smart-home-automation-a052e',
    authDomain: 'smart-home-automation-a052e.firebaseapp.com',
    databaseURL: 'https://smart-home-automation-a052e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-automation-a052e.appspot.com',
  );

}